# Generated by Django 4.0.3 on 2022-03-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_doner_blood_group_alter_doner_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doner',
            name='username',
        ),
    ]
