# Generated by Django 4.0.3 on 2022-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_doner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
